type: object
properties:
  id:
    type: string
    $ref: ./TrelloID.yaml
  idMemberCreator:
    type: string
    $ref: ./TrelloID.yaml
  data:
    type: object
    properties:
      text:
        type: string
        example: Can never go wrong with bowie
      card:
        type: object
        properties:
          id:
            type: string
            $ref: ./TrelloID.yaml
          name:
            type: string
            example: Bowie
          idShort:
            type: integer
            example: 7
          shortLink:
            type: string
            example: 3CsPkqOF
      board:
        type: object
        properties:
          id:
            type: string
            $ref: ./TrelloID.yaml
          name:
            type: string
            example: Mullets
          shortLink:
            type: string
            example: 3CsPkqOF
      list:
        type: object
        properties:
          id:
            type: string
            $ref: ./TrelloID.yaml
          name:
            type: string
            example: Amazing
  type:
    type: string
    example: commentCard
  date:
    type: string
    format: date-time
    example: '2020-03-09T19:41:51.396Z'
  limits:
    type: object
    properties:
      reactions:
        type: object
        properties:
          perAction:
            type: object
            properties:
              status:
                type: string
                example: ok
              disableAt:
                type: number
                example: 1000
              warnAt:
                type: number
                example: 900
          uniquePerAction:
            type: object
            properties:
              status:
                type: string
                example: ok
              disableAt:
                type: number
                example: 1000
              warnAt:
                type: number
                example: 900
  display:
    type: object
    properties:
      translationKey:
        type: string
        example: action_comment_on_card
      entities:
        type: object
        properties:
          contextOn:
            type: object
            properties:
              type:
                type: string
                example: translatable
              translationKey:
                type: string
                example: action_on
              hideIfContext:
                type: boolean
              idContext:
                type: string
                $ref: ./TrelloID.yaml
          card:
            type: object
            properties:
              type:
                type: string
                example: card
              hideIfContext:
                type: boolean
              id:
                type: string
                $ref: ./TrelloID.yaml
              shortLink:
                type: string
                example: 3CsPkqOF
              text:
                type: string
                example: Bowie
          comment:
            type: object
            properties:
              type:
                type: string
                example: comment
              text:
                type: string
                example: Can never go wrong with bowie
          memberCreator:
            type: object
            properties:
              type:
                type: string
                example: member
              id:
                $ref: ./TrelloID.yaml
              username:
                type: string
                example: bobloblaw
              text:
                type: string
                example: Bob Loblaw (World)
  memberCreator:
    type: object
    properties:
      id:
        type: string
        $ref: ./TrelloID.yaml
        example: 5b02e7f4e1facdc393169f9d
      activityBlocked:
        type: boolean
        example: false
      avatarHash:
        type: string
        example: db2adf80c2e6c26b76e1f10400eb4c45
      avatarUrl:
        type: string
        format: url
        example: >-
          https://trello-members.s3.amazonaws.com/5b02e7f4e1facdc393169f9d/db2adf80c2e6c26b76e1f10400eb4c45
      fullName:
        type: string
        example: Bob Loblaw (Trello)
      idMemberReferrer:
        type: string
        $ref: ./TrelloID.yaml
        nullable: true
        example: null
      initials:
        type: string
        example: BL
      username:
        type: string
        example: bobloblaw
